name: 'fsi_workshop'
version: '1.0.0'
config-version: 2
profile: 'snowflake_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

dbt-cloud:
    project-id: 21286
    defer-env-id: 40080

models:
  fsi_workshop:
    +static_analysis: strict
    +state:
      lag_tolerance: 24h
      require_fresh_data_from: any
    bronze:
      +materialized: view
      +tags: [bronze, fdic]
    silver:
      +tags: [silver, fdic]
      +state:
        lag_tolerance: 7d
        compare_unrendered_code: true
      int_fdic_deposits_exercise:
        +enabled: true
        +tags: [workshop_exercise]
      fct_fdic_institution_financials_exercise:
        +enabled: true
        +tags: [workshop_exercise]
    gold:
      +materialized: table
      +tags: [gold, fdic]
      +state:
        lag_tolerance: 7d
        compare_unrendered_code: true
      mart_fdic_institution_deposit_health_exercise:
        +enabled: true
        +tags: [workshop_exercise]
      mart_fdic_deposit_portfolio_exercise:
        +enabled: true
        +tags: [workshop_exercise]

flags:
  manage_state: true
